import { TarotCardInfo } from './types';

export const TAROT_DECK: TarotCardInfo[] = [
    // Major Arcana
    { name: 'The Fool', description: 'Beginnings, innocence, spontaneity, a free spirit.', image: '00.jpg' },
    { name: 'The Magician', description: 'Manifestation, resourcefulness, power, inspired action.', image: '01.jpg' },
    { name: 'The High Priestess', description: 'Intuition, sacred knowledge, divine feminine, the subconscious mind.', image: '02.jpg' },
    { name: 'The Empress', description: 'Femininity, beauty, nature, nurturing, abundance.', image: '03.jpg' },
    { name: 'The Emperor', description: 'Authority, establishment, structure, a father figure.', image: '04.jpg' },
    { name: 'The Hierophant', description: 'Spiritual wisdom, religious beliefs, conformity, tradition, institutions.', image: '05.jpg' },
    { name: 'The Lovers', description: 'Love, harmony, relationships, values alignment, choices.', image: '06.jpg' },
    { name: 'The Chariot', description: 'Control, willpower, success, action, determination.', image: '07.jpg' },
    { name: 'Strength', description: 'Courage, persuasion, influence, compassion.', image: '08.jpg' },
    { name: 'The Hermit', description: 'Soul-searching, introspection, being alone, inner guidance.', image: '09.jpg' },
    { name: 'Wheel of Fortune', description: 'Good luck, karma, life cycles, destiny, a turning point.', image: '10.jpg' },
    { name: 'Justice', description: 'Justice, fairness, truth, cause and effect, law.', image: '11.jpg' },
    { name: 'The Hanged Man', description: 'Pause, surrender, letting go, new perspectives.', image: '12.jpg' },
    { name: 'Death', description: 'Endings, change, transformation, transition.', image: '13.jpg' },
    { name: 'Temperance', description: 'Balance, moderation, patience, purpose.', image: '14.jpg' },
    { name: 'The Devil', description: 'Shadow self, attachment, addiction, restriction, sexuality.', image: '15.jpg' },
    { name: 'The Tower', description: 'Sudden change, upheaval, chaos, revelation, awakening.', image: '16.jpg' },
    { name: 'The Star', description: 'Hope, faith, purpose, renewal, spirituality.', image: '17.jpg' },
    { name: 'The Moon', description: 'Illusion, fear, anxiety, subconscious, intuition.', image: '18.jpg' },
    { name: 'The Sun', description: 'Positivity, fun, warmth, success, vitality.', image: '19.jpg' },
    { name: 'Judgement', description: 'Judgement, rebirth, inner calling, absolution.', image: '20.jpg' },
    { name: 'The World', description: 'Completion, integration, accomplishment, travel.', image: '21.jpg' },

    // Suit of Wands
    { name: 'Ace of Wands', description: 'Inspiration, new opportunities, growth, potential.', image: 'w01.jpg' },
    { name: 'Two of Wands', description: 'Future planning, progress, decisions, discovery.', image: 'w02.jpg' },
    { name: 'Three of Wands', description: 'Preparation, foresight, enterprise, expansion.', image: 'w03.jpg' },
    { name: 'Four of Wands', description: 'Celebration, harmony, marriage, home, community.', image: 'w04.jpg' },
    { name: 'Five of Wands', description: 'Conflict, disagreements, competition, tension, diversity.', image: 'w05.jpg' },
    { name: 'Six of Wands', description: 'Public recognition, victory, progress, self-confidence.', image: 'w06.jpg' },
    { name: 'Seven of Wands', description: 'Challenge, competition, perseverance, protective.', image: 'w07.jpg' },
    { name: 'Eight of Wands', description: 'Movement, speed, action, alignment, air travel.', image: 'w08.jpg' },
    { name: 'Nine of Wands', description: 'Resilience, courage, persistence, test of faith, boundaries.', image: 'w09.jpg' },
    { name: 'Ten of Wands', description: 'Burden, extra responsibility, hard work, completion.', image: 'w10.jpg' },
    { name: 'Page of Wands', description: 'Enthusiasm, exploration, discovery, free spirit.', image: 'w11.jpg' },
    { name: 'Knight of Wands', description: 'Energy, passion, inspired action, adventure, impulsiveness.', image: 'w12.jpg' },
    { name: 'Queen of Wands', description: 'Courage, confidence, independence, social butterfly, determination.', image: 'w13.jpg' },
    { name: 'King of Wands', description: 'Natural-born leader, vision, entrepreneur, honor.', image: 'w14.jpg' },

    // Suit of Cups
    { name: 'Ace of Cups', description: 'Love, new relationships, compassion, creativity.', image: 'c01.jpg' },
    { name: 'Two of Cups', description: 'Unified love, partnership, mutual attraction.', image: 'c02.jpg' },
    { name: 'Three of Cups', description: 'Celebration, friendship, creativity, collaborations.', image: 'c03.jpg' },
    { name: 'Four of Cups', description: 'Meditation, contemplation, apathy, re-evaluation.', image: 'c04.jpg' },
    { name: 'Five of Cups', description: 'Regret, failure, disappointment, pessimism.', image: 'c05.jpg' },
    { name: 'Six of Cups', description: 'Revisiting the past, childhood memories, innocence, joy.', image: 'c06.jpg' },
    { name: 'Seven of Cups', description: 'Opportunities, choices, wishful thinking, illusion.', image: 'c07.jpg' },
    { name: 'Eight of Cups', description: 'Disappointment, abandonment, withdrawal, escapism.', image: 'c08.jpg' },
    { name: 'Nine of Cups', description: 'Contentment, satisfaction, gratitude, wish come true.', image: 'c09.jpg' },
    { name: 'Ten of Cups', description: 'Divine love, blissful relationships, harmony, alignment.', image: 'c10.jpg' },
    { name: 'Page of Cups', description: 'Creative opportunities, intuitive messages, curiosity, possibility.', image: 'c11.jpg' },
    { name: 'Knight of Cups', description: 'Creativity, romance, charm, imagination, beauty.', image: 'c12.jpg' },
    { name: 'Queen of Cups', description: 'Compassionate, caring, emotionally stable, intuitive, in flow.', image: 'c13.jpg' },
    { name: 'King of Cups', description: 'Emotionally balanced, compassionate, diplomatic.', image: 'c14.jpg' },

    // Suit of Swords
    { name: 'Ace of Swords', description: 'Breakthroughs, new ideas, mental clarity, success.', image: 's01.jpg' },
    { name: 'Two of Swords', description: 'Difficult decisions, weighing up options, an impasse, avoidance.', image: 's02.jpg' },
    { name: 'Three of Swords', description: 'Heartbreak, emotional pain, sorrow, grief, hurt.', image: 's03.jpg' },
    { name: 'Four of Swords', description: 'Rest, relaxation, meditation, contemplation, recuperation.', image: 's04.jpg' },
    { name: 'Five of Swords', description: 'Conflict, tension, loss, defeat, winning at all costs.', image: 's05.jpg' },
    { name: 'Six of Swords', description: 'Transition, change, rite of passage, releasing baggage.', image: 's06.jpg' },
    { name: 'Seven of Swords', description: 'Betrayal, deception, getting away with something, acting strategically.', image: 's07.jpg' },
    { name: 'Eight of Swords', description: 'Negative thoughts, self-imposed restriction, imprisonment, victim mentality.', image: 's08.jpg' },
    { name: 'Nine of Swords', description: 'Anxiety, worry, fear, depression, nightmares.', image: 's09.jpg' },
    { name: 'Ten of Swords', description: 'Painful endings, deep wounds, betrayal, loss, crisis.', image: 's10.jpg' },
    { name: 'Page of Swords', description: 'New ideas, curiosity, thirst for knowledge, new ways of communicating.', image: 's11.jpg' },
    { name: 'Knight of Swords', description: 'Ambitious, action-oriented, driven to succeed, fast-thinking.', image: 's12.jpg' },
    { name: 'Queen of Swords', description: 'Independent, unbiased judgement, clear boundaries, direct communication.', image: 's13.jpg' },
    { name: 'King of Swords', description: 'Mental clarity, intellectual power, authority, truth.', image: 's14.jpg' },

    // Suit of Pentacles
    { name: 'Ace of Pentacles', description: 'A new opportunity, manifestation, prosperity.', image: 'p01.jpg' },
    { name: 'Two of Pentacles', description: 'Multiple priorities, time management, prioritization, adaptability.', image: 'p02.jpg' },
    { name: 'Three of Pentacles', description: 'Teamwork, collaboration, learning, implementation.', image: 'p03.jpg' },
    { name: 'Four of Pentacles', description: 'Saving money, security, conservatism, scarcity, control.', image: 'p04.jpg' },
    { name: 'Five of Pentacles', description: 'Financial loss, poverty, lack mindset, isolation, worry.', image: 'p05.jpg' },
    { name: 'Six of Pentacles', description: 'Giving, receiving, sharing wealth, generosity, charity.', image: 'p06.jpg' },
    { name: 'Seven of Pentacles', description: 'Long-term view, sustainable results, perseverance, investment.', image: 'p07.jpg' },
    { name: 'Eight of Pentacles', description: 'Apprenticeship, repetitive tasks, mastery, skill development.', image: 'p08.jpg' },
    { name: 'Nine of Pentacles', description: 'Abundance, luxury, self-sufficiency, financial independence.', image: 'p09.jpg' },
    { name: 'Ten of Pentacles', description: 'Wealth, financial security, family, long-term success, contribution.', image: 'p10.jpg' },
    { name: 'Page of Pentacles', description: 'Manifestation, financial opportunity, skill development.', image: 'p11.jpg' },
    { name: 'Knight of Pentacles', description: 'Hard work, productivity, routine, conservatism.', image: 'p12.jpg' },
    { name: 'Queen of Pentacles', description: 'Nurturing, practical, providing financially, a working parent.', image: 'p13.jpg' },
    { name: 'King of Pentacles', description: 'Wealth, business, leadership, security, discipline, abundance.', image: 'p14.jpg' },
];